### ISSUE TITLE
All text disappears when I git clone and compile on my system

### ISSUE THREAD

**Issue by thehalfspace** [FuzzyWuzzie/Beamer-Theme-Execushares#6]
I cloned this repo and tried to compile it after changing the title. The output pdf just has the bare theme with no text. Am I missing any required packages? 

When I comment out the theme `\usetheme{Execushare}` it works fine.

I am using texShop on mac and compiling using vimtex and viewing using skim.

**Comment by hamaluik** [comment]
It’s been a long time since I’ve worked on this but it sounds most likely that you’re missing the fonts.. If I recall correctly you also might need to compile using xetex instead of regular latex.

You could try commenting out the lines here: https://github.com/hamaluik/Beamer-Theme-Execushares/blob/master/beamerthemeExecushares.sty#L26-L34 to see if that changes anything.

**Comment by thehalfspace** [comment]
Ahh thanks! I just figured out minutes ago that I was missing fonts. I'll try installing the fonts or using some other fonts.
